apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:latest
        env:
        - name: HOST
          value: postgres
        - name: USER
          value: odoo
        - name: PASSWORD
          value: O9E8FD20was*
        - name: DBNAME
          value: odoo
        command: ["odoo", "-i", "base"]
        ports:
        - containerPort: 8069
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
